### ISSUE TITLE
Button Style on Site Visit form

### ISSUE THREAD

**Issue by jcaraballo17** [UCHIC/ODM2Sensor#123]
The "Add Action" button in the Site Visit form has a fixed width that is smaller than the text.

**Comment by ZachYoshikawa** [comment]
Button is the correct size on the master branch, but not on the website online.

**Comment by horsburgh** [comment]
Let's not close issues until they are at least working in the deployment on the sanbox server.  Instead add appropriate labels:

"fixed" - The code has been fixed and merged with the master branch
"ready for testing" - the fix has been deployed on the sandbox server and is ready to be tested.  

Once tested, issues can be closed.  Best would be to close them when working on the production server.

**Comment by ZachYoshikawa** [comment]
Okay, good to know.

**Comment by AmberSJones** [comment]
When at full width, this appears to be fixed, but the issue is still there when the window is resized to a smaller width:
![image](https://cloud.githubusercontent.com/assets/5023186/10983727/89102fc8-83d1-11e5-9b9d-58ad062c19d0.png)

**Comment by ZachYoshikawa** [comment]
@AmberSJones it should be working this time!

**Comment by AmberSJones** [comment]
Great. Closing.
