### ISSUE TITLE
Server Error when trying to update Generic Action

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#189]
I get a server error when trying to update a generic action. Once in a while the edit/update works, but usually it gives Server Error. I think it may have to do with adding equipment or not, but I can't identify a pattern with it.

![image](https://cloud.githubusercontent.com/assets/5023186/13819912/d2a07a2a-eb60-11e5-8057-d5dcd26b77b5.png)

**Comment by AmberSJones** [comment]
This may be the same as issue #171

**Comment by ZachYoshikawa** [comment]
This issue appears to be the same as #171 . The javascript function in comomon_forms.js was not filtering the equipment used section correctly. It is fixed now.

**Comment by AmberSJones** [comment]
This is still occurring for me. I can now successfully edit generic actions, but I get server error when creating. It appears to only occur for actions for which I don't specify equipment (i.e., it is not required to specify equipment for actions of type specimen collection or field activity).

![image](https://cloud.githubusercontent.com/assets/5023186/14084971/7ea856c6-f4da-11e5-8f39-a122abc5c9e9.png)

**Comment by jcaraballo17** [comment]
There was something weird with the equipment used validation.

**Comment by AmberSJones** [comment]
I continue to get server error when I try to edit any generic action for which equipment was used. 
![image](https://cloud.githubusercontent.com/assets/5023186/15874502/a912ca0e-2cc0-11e6-85a7-24103dc6a9a3.png)

**Comment by AmberSJones** [comment]
I can create a generic action that uses equipment, but I cannot edit it.

**Comment by AmberSJones** [comment]
I'm still having this issue. Created a generic action and was then unable to edit it. This is only an issue if the Action uses Equipment.

![image](https://cloud.githubusercontent.com/assets/5023186/19574846/374461bc-96c9-11e6-90d8-bbef3a6d159e.png)

**Comment by AmberSJones** [comment]
This appears to be addressed.
