### ISSUE TITLE
Weirdness when editing site visit

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#204]
I create a site visit. Then, from the summary page, I click on the 'Edit Site Visit' button. Some of the fields are incorrectly populated (for example, there is no equipment selected for the deployments that I created). Furthermore, there are no results being created for the Instrument deployment actions.
![image](https://cloud.githubusercontent.com/assets/5023186/19577431/90c9a1c4-96d4-11e6-89a1-6abc21ecaa6a.png)

**Comment by Elijahwalkerwest** [comment]
This was fixed alongside #168. Currently working on my local env. I will fix a few more of these issues and deploy them altogether to the sandbox for testing.

**Comment by Elijahwalkerwest** [comment]
Ready for testing.

**Comment by AmberSJones** [comment]
This is still occurring for me- with some changes. 

I create a site visit. Then, from the summary page, I click on the 'Edit Site Visit' button. 
![image](https://cloud.githubusercontent.com/assets/5023186/24910170/243320e8-1e84-11e7-919b-8f176de842a8.png)

The same actions that I had created are there, and the equipment is correctly selected.  However, the "Results" are not as expected. For one action, there is no Result present. For another action, the Results have incorrect variables selected.

![image](https://cloud.githubusercontent.com/assets/5023186/24910208/4856810e-1e84-11e7-915e-fc1b8be58471.png)

**Comment by Elijahwalkerwest** [comment]
Fixed with latest deployment.

**Comment by AmberSJones** [comment]
This appears to be addressed.
