### ISSUE TITLE
Issues creating multiple results

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#230]
Created a site visit with multiple new results. When I then try to edit the site visit, it only retains the first new result. The others are highlighted as problematic.

**Comment by Elijahwalkerwest** [comment]
Should be fixed and ready for testing.

**Comment by AmberSJones** [comment]
Still having issues with Creating a site visit with multiple new results.

**Comment by AmberSJones** [comment]
I'm actually going to close this one. I think this specific issue is addressed, but there are others documented in other issues.
