### ISSUE TITLE
Unable to create retrieval

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#243]
I tried to retrieve equipment. Got an error.

![image](https://user-images.githubusercontent.com/5023186/34802256-edc37d9a-f629-11e7-8de1-206eb2f2bbbd.png)

**Comment by Elijahwalkerwest** [comment]
Should be resolved and ready for testing.

**Comment by AmberSJones** [comment]
Still getting an error when trying to retrieve.
![image](https://user-images.githubusercontent.com/5023186/36757421-b9e77998-1bce-11e8-89f0-bf3c90e069b0.png)

**Comment by AmberSJones** [comment]
Yep, still occurring.

**Comment by Elijahwalkerwest** [comment]
Resolved. Sorry, retrieve from deployment and create retrieval pass in two different variables, and I hadn't accounted for that. Fixed and pushing.

**Comment by Elijahwalkerwest** [comment]
Fixed and pushed.

**Comment by AmberSJones** [comment]
Still having trouble when trying to retrieve from the deployment.
![image](https://user-images.githubusercontent.com/5023186/37682149-5820fec4-2c4e-11e8-96c0-2d275aab7da3.png)

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing!

**Comment by AmberSJones** [comment]
I just started a new issue indicating that sometimes Retrievals are not working, so I will close this issue.
