### ISSUE TITLE
Need to be able to create retrievals from the Site Visit page

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#246]
On the site visit page, I can add new Calibrations, Deployments, and Other Actions. When I try to use "Add Another Action" to add a retrieval, I am unable to as Retrievals are not one of the Action types permitted for selection. This should be added.

**Comment by Elijahwalkerwest** [comment]
Fixed!

**Comment by Elijahwalkerwest** [comment]
Deployed and ready to test.

**Comment by AmberSJones** [comment]
Retrievals still do not appear in the list of Action Types.

![image](https://user-images.githubusercontent.com/5023186/36758493-ddc1192a-1bd1-11e8-94d4-fb0f68be585f.png)

**Comment by Elijahwalkerwest** [comment]
Product of me forgeting to collectstatic. Will be resolved when thats done.

**Comment by Elijahwalkerwest** [comment]
Update done, ready for testing.

**Comment by AmberSJones** [comment]
This is addressed.
